<?php $title_for_layout = $page->name ?>
<div class="col-md-10 col-lg-10" style="padding-left:250px">
<br>
<h2 class="c-font-uppercase c-font-bold">Contrat d’utilisation (conditions d’utilisation du site web smartlife.com)</h2>

            
           
<p>&nbsp;</p>
<p>Ces conditions d'utilisation sont une offre publique. Pour utiliser les services fournis par le site web, vous devez accepter de vous conformer aux conditions stipul&eacute;es dans le pr&eacute;sent document. Votre utilisation du site https://smartlife.com implique que vous acceptez ces conditions et que vous vous y conformez. Si vous n'&ecirc;tes pas d'accord avec ces conditions, vous ne pouvez pas utiliser le site web ni les services de quelque mani&egrave;re que ce soit. Vous acceptez que Goteam SARL consid&egrave;re que le fait d'utiliser le site web constitue votre plein accord avec les conditions actuellement stipul&eacute;es aux pr&eacute;sentes.</p>
<p>&nbsp;</p>
<p>En ouvrant un compte avec le site https://smartlife.com, l'utilisateur assume la responsabilit&eacute; de se conformer &agrave; toutes les conditions stipul&eacute;es dans le pr&eacute;sent Contrat d'utilisation, ainsi qu'aux conditions d'utilisation. Tous les nouveaux outils et fonctionnalit&eacute;s qui peuvent &ecirc;tre ajout&eacute;s aux services doivent &ecirc;tre conformes aux pr&eacute;sentes Conditions d'utilisation. Vous pouvez prendre connaissance de la derni&egrave;re version des Conditions d'utilisation &agrave; tout moment sur cette page. Nous nous r&eacute;servons le droit d'apporter des amendements et de modifier les conditions des services en mettant &agrave; jour ces Conditions d'utilisation. Nous vous recommandons de v&eacute;rifier ces Conditions d'utilisation de temps &agrave; autre afin de prendre connaissance des nouvelles conditions &eacute;ventuelles qui pourraient ou non vous concerner. Ces conditions sont importantes, car elles sont l&eacute;galement mutuellement contraignantes.</p>
<p>Nos services sont dirig&eacute;s par une plate-forme facile &agrave; utiliser qui assure &agrave; l&rsquo;utilisateur un contr&ocirc;le total de son compte y compris le financement, l&rsquo;achat &nbsp;et la vente du produit. Apr&egrave;s l&rsquo;inscription initiale, l&rsquo;utilisateur utilise son compte sous sa propre responsabilit&eacute; et en aucun cas la soci&eacute;t&eacute; n&rsquo;est responsable envers une personne ou une entit&eacute; de pertes ou de dommages caus&eacute;es par les op&eacute;rations sur la plate-forme. En aucun cas les commandes ne peuvent &ecirc;tre annul&eacute;es, supprim&eacute;es ou rembours&eacute;es une fois confirm&eacute;es par l&rsquo;utilisateur. Chaque utilisateur doit lire attentivement la directive de remboursement de Smartlife, tutoriels et pages Foire aux Questions avant de s&rsquo;engager. Pour toutes les questions ou pr&eacute;occupations, l&rsquo;utilisateur doit nous contacter via notre support pour de plus amples informations.</p>
<p>&nbsp;</p>
<p>Goteam Sarl. , qui agit comme payeur de l'imp&ocirc;t sur le revenu, &nbsp;conform&eacute;ment au Code fiscal de la R&eacute;publique de C&ocirc;te d&rsquo;Ivoire ( <strong>GOTEAM, situ&eacute; &agrave; Abidjan Cocody Angr&eacute; 9<sup>&egrave;me</sup> tranche vers la CNPS, immeuble TERE Lot 703/ilot 31/01 BP 10733 ABJ 01/ Tel +225 45462347/ +225 51505090/+225 22010430/ RCCM&nbsp;: CI-ABJ-2016-B-24324/CC:1646960Q </strong>), ci-apr&egrave;s le Prestataire, agissant conform&eacute;ment &nbsp;&agrave; la base de la charte de la Soci&eacute;t&eacute; et de l&rsquo;union internationale des t&eacute;l&eacute;communications, en tant que premi&egrave;re partie, et l'utilisateur, ci-apr&egrave;s, le Client, agissant en vertu de la l&eacute;gislation civile et fiscale de son pays ainsi que des documents d'application de la r&eacute;glementation internationale, en tant que seconde partie, ont sign&eacute; le pr&eacute;sent Accord de service, ci-apr&egrave;s, l'Accord ou le Contrat, en utilisant les moyens de communication num&eacute;rique &eacute;lectronique sur la base suivante :</p>
<p>Les conditions du compte :</p>
<p>Vous devez avoir l&rsquo;&acirc;ge de la majorit&eacute; dans le pays que vous habitez afin de pouvoir utiliser les Services fournis par le site https://smartlife.com</p>
<p>&nbsp;</p>
<p>Afin de se conformer aux normes internationales, Goteam sarl doit v&eacute;rifier votre identit&eacute;, ce qui implique de demander des renseignements d'identification suffisants pour v&eacute;rifier l'identit&eacute;, l'adresse, l'emplacement et une photographie r&eacute;cente du client. Pour les clients qui sont des personnes morales, Goteam SARL devra (i) v&eacute;rifier le statut juridique de la personne morale au moyen de justificatifs appropri&eacute;s et pertinents ; (ii) v&eacute;rifier que toute personne pr&eacute;tendant agir au nom de l&rsquo;entit&eacute; morale est autoris&eacute;e, puis identifier et v&eacute;rifier l'identit&eacute; de cette personne ; (iii) comprendre la structure de propri&eacute;t&eacute; et de contr&ocirc;le du client et d&eacute;terminer qui sont les personnes physiques qui contr&ocirc;lent en final la personne morale. Goteam SARL peut &eacute;galement proc&eacute;der &agrave; une v&eacute;rification de la propri&eacute;t&eacute; des cartes de cr&eacute;dit quand elles sont utilis&eacute;es pour financer un compte Smart Life. Cette v&eacute;rification peut &eacute;galement &ecirc;tre demand&eacute;e &agrave; des utilisateurs qui ont &eacute;t&eacute; v&eacute;rifi&eacute;s dans le pass&eacute;.</p>
<p>&nbsp;</p>
<p>Vous devez &ecirc;tre un &ecirc;tre humain. Les comptes enregistr&eacute;s par des &laquo; robots &raquo; ou autres m&eacute;thodes automatis&eacute;es ne sont pas autoris&eacute;s. Vous n'&ecirc;tes pas autoris&eacute; &agrave; cr&eacute;er plusieurs comptes.</p>
<p>&nbsp;</p>
<p>Les comptes inactifs qui n&rsquo;ont pas &eacute;t&eacute; utilis&eacute;s depuis 60 jours cons&eacute;cutifs ou dont le profil n&rsquo;a pas &eacute;t&eacute; enti&egrave;rement rempli seront automatiquement &eacute;limin&eacute;s. Les comptes inactifs sont ceux sans d&eacute;p&ocirc;t actif propre.</p>
<p>&nbsp;</p>
<p>Vous devez fournir une adresse &eacute;lectronique valide ainsi que toute autre information n&eacute;cessaire afin de compl&eacute;ter le processus d'inscription ;</p>
<p>&nbsp;</p>
<p>Vous et vous seulement &ecirc;tes responsables de garder votre mot de passe en s&eacute;curit&eacute;. Goteam SARL &nbsp;d&eacute;cline toute responsabilit&eacute; en cas de pertes mat&eacute;rielles ou de dommages de tout type r&eacute;sultant de votre incapacit&eacute; &agrave; garder votre compte et votre mot de passe en s&eacute;curit&eacute; ;</p>
<p>Si vous avez d&eacute;couvert une utilisation ill&eacute;gale ou non autoris&eacute;e de votre mot de passe ou de votre compte, vous pouvez en informer par courriel sans d&eacute;lai <a href="https://goteam-ci.com/contacts/">Goteam SARL </a>; Vous acceptez donc votre responsabilit&eacute; pour toutes les actions effectu&eacute;es en utilisant votre compte ;</p>
<p>Vous convenez que vous n'utiliserez pas les services fournis par <a href="https://smartlife.com/contacts/">Smart Life.</a> pour tout type d'activit&eacute; ou finalit&eacute; non autoris&eacute; ou ill&eacute;gal, ainsi que pour tout ce qui va &agrave; l'encontre de la l&eacute;gislation de votre pays</p>
<p>Vous et vous seulement &ecirc;tes responsable du type de contenu que vous t&eacute;l&eacute;versez sur le site web, en particulier les images, les donn&eacute;es, les graphiques et les liens, et vous garantissez que vous d&eacute;tenez les droits d'utilisation applicable du contenu que vous t&eacute;l&eacute;versez sur le site web ;</p>
<p>Vous ne t&eacute;l&eacute;verserez ou n'utiliserez pas sur le site web des logiciels malveillants, virus, ou code destructeur ;</p>
<p>Vous n'&ecirc;tes pas autoris&eacute; &agrave; payer des bonus, des remboursements ou des r&eacute;compenses &agrave; des partenaires en aval. Toute activit&eacute; de ce genre conduira &agrave; la suspension d&eacute;finitive de votre compte.</p>
<p>Tout manquement &agrave; ces conditions, dont la r&eacute;alit&eacute; sera examin&eacute;e discr&egrave;tement par Goteam SARL, conduira &agrave; l'arr&ecirc;t de votre utilisation du site.</p>
<p>Les fonds provenant de comptes bloqu&eacute;s ne peuvent pas &ecirc;tre rembours&eacute;s si les conditions de service ont &eacute;t&eacute; viol&eacute;es. Nous nous r&eacute;servons le droit de les utiliser pour des &oelig;uvres de bienfaisance ou d'autres projets selon ce que va d&eacute;cider la direction.</p>
<p><strong>Comptes d'entreprise :</strong></p>
<p>Il n&rsquo;est pas possible de convertir des comptes individuels en comptes d&rsquo;entreprise ; si l&rsquo;ouverture d&rsquo;un compte d&rsquo;entreprise vous int&eacute;resse, vous devrez ouvrir un nouveau compte.</p>
<p>Pour demander un compte d'entreprise, vous devrez cr&eacute;er ce compte en vous connectant &agrave; <a href="https://smartlife.com/signcorp/">https://smartlife.com/signcorp/</a>.</p>
<p>Le d&eacute;p&ocirc;t minimal pour les comptes d'entreprise est de 20 000 euros. Lors de l'enregistrement du compte d'entreprise, il vous sera demand&eacute; de nous fournir les justificatifs suivants : preuve d'inscription l&eacute;gale de votre entreprise, pi&egrave;ce d'identit&eacute; du directeur, num&eacute;ro de TVA et donn&eacute;es du compte bancaire de votre entreprise.</p>
<p>Nous vous demanderons de d&eacute;poser 100 EUR de mani&egrave;re &agrave; v&eacute;rifier vos documents. Si votre compte est approuv&eacute;, ce d&eacute;p&ocirc;t sera cr&eacute;dit&eacute; sur votre nouveau compte. Si la demande est rejet&eacute;e (par exemple pour des fausses informations, compte bancaire ayant d&eacute;j&agrave; &eacute;t&eacute; utilis&eacute; pour alimenter un autre compte, etc.), ce d&eacute;p&ocirc;t sera consid&eacute;r&eacute; comme frais de gestion.</p>
<p>Les comptes d'entreprise ne devront pas faire partie de structure pyramidale, ni en amont, ni en aval.</p>
<p>Une soci&eacute;t&eacute; ne peut ouvrir qu'un seul compte d'entreprise.</p>
<p>Il ne sera possible &agrave; aucun moment de convertir un compte d'entreprise en un compte individuel.</p>
<ol>
<li><strong> PORT&Eacute;E DE L'ACCORD</strong>
<ul>
<li>Sous r&eacute;serve des dispositions du pr&eacute;sent Accord, le Prestataire doit&nbsp;:</li>
</ul>
</li>
</ol>
<p>Fournir aux clients les diff&eacute;rents services, &nbsp;li&eacute;s &agrave; l'utilisation de l&rsquo;application smartlife situ&eacute;e sur le site https://smartlife.com.</p>
<p>Cr&eacute;er &nbsp;l'interface qui permettra aux membres de passer des commandes et/ou d&rsquo;acheter des marchandises sur le site, elles-m&ecirc;mes achet&eacute;es aupr&egrave;s de tiers.</p>
<p>1.2. Les paiements des marchandises achet&eacute;es aupr&egrave;s de tiers en utilisant le site web sont effectu&eacute;s exclusivement entre le Prestataire et les tiers. Dans les cas o&ugrave; Goteam Sarl. agirait comme agent fournisseur, acheteur &nbsp;et/ou acheteur du Prestataire, ces relations seront r&eacute;gies par l'accord s&eacute;par&eacute;.</p>
<p>1.3. Les b&eacute;n&eacute;fices offerts sont bas&eacute;s sur un calcul qui prend en compte le prix d'achat de la marchandise et le prix de vente obtenu pour le produit final. Le b&eacute;n&eacute;fice offert est annonc&eacute; sur le site <a href="https://smartlife.com">https://smartlife.com</a></p>
<p>1.5. Les fluctuations du prix d'achat des biens et services ainsi que les frais de transport peuvent se r&eacute;percuter sur les clients.</p>
<p>1.6. Goteam Sarl. est en droit de facturer au client l'utilisation de sa logistique et/ou de ses installations de production &agrave; un prix raisonnable</p>
<p>&nbsp;1.7. Au cas o&ugrave; le prix des biens et services propos&eacute;s&nbsp; grimpe &agrave; un certain niveau ou que la &nbsp;qualit&eacute; de ceux-ci&nbsp; s&rsquo;av&egrave;re &ecirc;tre&nbsp; &nbsp;inf&eacute;rieure &agrave; la norme,&nbsp;&nbsp; &nbsp;Goteam Sarl&nbsp; se r&eacute;serve le droit de changer le co&ucirc;t pr&eacute;&eacute;tabli.</p>
<ol start="2">
<li><strong> RESPONSABILIT&Eacute;S ET DROITS DU PRESTATAIRE</strong></li>
</ol>
<p>2.1. Sous r&eacute;serve des dispositions du pr&eacute;sent Accord, le Prestataire devra :</p>
<p>2.1.1 Enregistrer les donn&eacute;es du Client sur le site <a href="https://smartlife.com">https://smartlife.com</a> et fournir au Client des recommandations concernant l'utilisation de l'espace Membre et la passation des commandes ;</p>
<p>2.1.2 Fournir en permanence au client des services de conseil pour l'utilisation de l&rsquo;application.</p>
<p>2.2. Le Prestataire est en droit de :</p>
<p>2.2.1. Refuser de fournir au client les services pr&eacute;vus &agrave; l'article 1.1 du pr&eacute;sent Accord dans le cas o&ugrave; le client ne remplirait pas les conditions de l'Accord ou le remplirait de mani&egrave;re incorrecte ;</p>
<p>2.2.2. Apporter des amendements &agrave; ces conditions d'utilisation &agrave; sa seule discr&eacute;tion et fournir au client la possibilit&eacute; de les examiner sur le site web ;</p>
<p>2.2.3. Contr&ocirc;ler le respect des responsabilit&eacute;s du Client qui sont contenues dans le pr&eacute;sent document.</p>
<ol start="3">
<li><strong> RESPONSABILIT&Eacute;S ET DROITS DU CLIENT</strong></li>
</ol>
<p>3.1. Le client devra :</p>
<p>3.1.1. R&eacute;guli&egrave;rement mettre &agrave; jour le catalogue de marchandises dans le but de comparer les prix ;</p>
<p>3.1.2. Respecter les conditions d'utilisation du site web ;</p>
<p>3.1.3. Effectuer des paiements pour les services du Prestataire en temps voulu, selon les conditions et le montant pr&eacute;vus &agrave; l'article 4 du pr&eacute;sent Accord ;</p>
<p>3.1.4. D&eacute;signer des repr&eacute;sentants l&eacute;gaux responsables de l'utilisation de l&rsquo;application et en aviser le Prestataire, le cas &eacute;ch&eacute;ant.</p>
<p>3.2. Le client a le droit de :</p>
<p>3.2.1. Contr&ocirc;ler le respect des responsabilit&eacute;s du Prestataire d&eacute;crites dans le pr&eacute;sent document ;</p>
<p>3.2.2. Recevoir une assistance de conseil du Prestataire sur les demandes envoy&eacute;es &agrave; l'adresse &eacute;lectronique du Prestataire.</p>
<h2>4. RELATIONS FINANCI&Egrave;RES</h2>
<p>4.1. Les frais des services que le Prestataire fournit au Client sont d&eacute;finis en conformit&eacute; avec les donn&eacute;es analytiques figurant sur le site ; ils sont en pourcentage de la quantit&eacute; de tous les produits vendus par le Client et repr&eacute;sentent 25 &agrave; 50 %.</p>
<p>4.2. Le paiement des services soumis au pr&eacute;sent Accord est effectu&eacute; en m&ecirc;me temps que le paiement du montant des marchandises vendues par le Client en esp&egrave;ces en le d&eacute;duisant du montant d&ucirc; au Client. Si cette d&eacute;duction ne peut &ecirc;tre faite, le paiement des services sera effectu&eacute; dans les cinq jours ouvrables apr&egrave;s que le Client ai re&ccedil;u la demande de paiement du Prestataire.</p>
<p>4.3. Apr&egrave;s les services fournis, un certificat d'acceptation de prestation peut &ecirc;tre produit. En cas de non-signature du certificat par le Client dans les 3 jours ouvrables suivant la date de sa r&eacute;ception et de la non-r&eacute;ception du refus raisonnable du client dans ce d&eacute;lai, le certificat sera consid&eacute;r&eacute; comme sign&eacute; et les services seront consid&eacute;r&eacute;s comme fournis dans leur int&eacute;gralit&eacute; par le Prestataire sous r&eacute;serve des dispositions du pr&eacute;sent Accord.</p>
<p>4.4. En cas de prestation de services suppl&eacute;mentaires par le Prestataire, les calculs finaux sont effectu&eacute;s par le Client sous r&eacute;serve de l'accord suppl&eacute;mentaire.</p>
<p>4.5. Le Prestataire se r&eacute;serve le droit d'apporter des amendements &agrave; la politique de prix via la publication de la tarification mise &agrave; jour sur le site web et/ou en informant le Client par courriel.</p>
<p>4.6. Chaque Partie a la responsabilit&eacute; de se conformer aux exigences du code fiscal et, sur la base d'une coop&eacute;ration mutuellement b&eacute;n&eacute;fique, doit consulter l'autre et &eacute;galement des tiers afin d'&ecirc;tre des contribuables respectueux de la loi et de s'entraider en signant les documents respectifs, le cas &eacute;ch&eacute;ant.</p>
<p>4.7. Sous r&eacute;serve du pr&eacute;sent Accord, le Prestataire n'est pas tenu responsable de la coop&eacute;ration du Client avec des fournisseurs et des acheteurs utilisant le site web, et ne contr&ocirc;lera pas la r&eacute;alisation de tout type d'offres et d'accords, ni l'utilisation pr&eacute;vue des fonds, ni le r&egrave;glement de tout type de litiges ou d'incoh&eacute;rences. Le Prestataire utilise les services de tiers, tels que banques, syst&egrave;mes de paiement &eacute;lectronique, institutions financi&egrave;res ou autres, &agrave; des fins de collecte de fonds et ne peut donc &ecirc;tre tenu responsable de la fourniture de ces services par des tiers, mais fera tout en son pouvoir pour que le client re&ccedil;oive ces services. Le Prestataire ne peut pas influer sur la politique de tarification des syst&egrave;mes de paiement et donc le Client doit choisir ind&eacute;pendamment d'utiliser les services de l'un des syst&egrave;mes de paiement disponibles et s'informer de sa propre initiative aupr&egrave;s des sources d'information concernant les syst&egrave;mes de paiement et les banques correspondants.</p>
<h2>5. RESPONSABILIT&Eacute; DES PARTIES</h2>
<p>5.1. Les Parties ont une responsabilit&eacute; dans les affaires juridiques et sont soumises &agrave; la l&eacute;gislation en vigueur dans la R&eacute;publique de C&ocirc;te d&rsquo;Ivoire.</p>
<p>5.2. Les parties ont une responsabilit&eacute; soumise &agrave; la l&eacute;gislation en vigueur dans la R&eacute;publique de C&ocirc;te d&rsquo;Ivoire en cas de non-ex&eacute;cution ou d'ex&eacute;cution inad&eacute;quate de dispositions du pr&eacute;sent Accord. Toute violation d'obligation revient &agrave; sa non-ex&eacute;cution ou ex&eacute;cution insuffisante, c'est-&agrave;-dire une ex&eacute;cution comportant une violation des conditions stipul&eacute;es aux pr&eacute;sentes.</p>
<p>5.3. La Partie sera consid&eacute;r&eacute;e comme innocente si elle peut prouver que tous les moyens n&eacute;cessaires ont &eacute;t&eacute; mis en place pour respecter les obligations.</p>
<p>5.4. Le paiement des frais ou de la commission selon cet Accord de la l&eacute;gislation de la R&eacute;publique de C&ocirc;te d&rsquo;Ivoire ne lib&egrave;re pas les Parties de la responsabilit&eacute; de l'ex&eacute;cution de l'obligation qui leur incombe en vertu du pr&eacute;sent Accord.</p>
<p>5.5. En cas de retard de paiement par le Client en vertu du pr&eacute;sent Accord, le Client doit payer des int&eacute;r&ecirc;ts moratoires quotidiens repr&eacute;sentant 0,1 % du montant du passif total en retard.</p>
<p>5.6. Aucune des Parties ne peut &ecirc;tre tenue responsable de la non-r&eacute;alisation des engagements vis&eacute;s par le pr&eacute;sent Accord si elle est due &agrave; des circonstances de force majeure telles que l'&eacute;tat d'urgence, une catastrophe naturelle, ainsi que d'autres circonstances d&eacute;passant le contr&ocirc;le raisonnable d'une partie. Ces circonstances doivent &ecirc;tre confirm&eacute;es par l'organisme gouvernemental comp&eacute;tent.</p>
<p>5.7. En cas d'impossibilit&eacute; de fournir les services command&eacute;s par le Client en raison d'une d&eacute;faillance technique de longue dur&eacute;e, le Prestataire se r&eacute;serve le droit de r&eacute;silier le contrat sans indemnit&eacute;s de retard.</p>
<h2>6. R&Egrave;GLEMENT DES DIFF&Eacute;RENDS</h2>
<p>6.1. Les diff&eacute;rends qui pourraient appara&icirc;tre dans le processus d'ex&eacute;cution du pr&eacute;sent Accord seront r&eacute;gl&eacute;s par n&eacute;gociation entre les Parties.</p>
<p>6.2. Toutes les plaintes &eacute;ventuelles associ&eacute;es au pr&eacute;sent Accord seront examin&eacute;es par les parties, conform&eacute;ment &agrave; la l&eacute;gislation de la R&eacute;publique de C&ocirc;te d&rsquo;Ivoire.</p>
<p>6.3. Les diff&eacute;rends qui ne sont pas r&eacute;gl&eacute;s par les Parties seront r&eacute;gl&eacute;s par des proc&eacute;dures judiciaires, selon la comp&eacute;tence juridictionnelle en conformit&eacute; avec la documentation actuelle et le droit proc&eacute;dural de la R&eacute;publique de C&ocirc;te d&rsquo;Ivoire.</p>
<p>6.4. Le Prestataire n'est ni un tribunal ni un conseil d'arbitrage et ne participe &agrave; aucun r&egrave;glement de litiges entre les Clients, se r&eacute;servant le droit de collecter les informations n&eacute;cessaires sur les litiges qui se manifestent.</p>
<h2>7. DUR&Eacute;E ET R&Eacute;SILIATION DU CONTRAT</h2>
<p>7.1. Le pr&eacute;sent Accord prend effet lors de l'inscription du Client sur le site Web, qui participe au pr&eacute;sent Accord public sous la forme d'un document &eacute;lectronique &eacute;crit et qui reste en vigueur pendant l'utilisation du Service par le Client. &Agrave; la fin du processus d'inscription, le Client devient l'une des Parties du pr&eacute;sent Accord et a la responsabilit&eacute; de se conformer aux exigences stipul&eacute;es aux pr&eacute;sentes. Si le Client s'inscrit sur le site Web au nom d'une autre personne priv&eacute;e ou morale, le Client doit affirmer et garantir qu'il a les pleins pouvoirs et les droits d'accepter la responsabilit&eacute; stipul&eacute;e aux pr&eacute;sentes au nom de ces tiers.</p>
<p>7.2. Le Client n'a pas le droit de d&eacute;l&eacute;guer ses droits ou obligations en vertu du pr&eacute;sent Accord &agrave; un tiers sans avoir re&ccedil;u l'autorisation &eacute;crite pr&eacute;alable du Prestataire.</p>
<p>7.3. Aux fins de l'ex&eacute;cution du pr&eacute;sent Accord, les Parties &eacute;changent des informations concernant leurs int&eacute;r&ecirc;ts mutuels et se fournissent mutuellement des services de conseil si n&eacute;cessaire.</p>
<p>&nbsp;7.4. Le client ou l&rsquo;entrepreneur a le droit de r&eacute;silier ce contrat &agrave; tout moment pour quelque raison que ce soit, tout en tenant inform&eacute; l&rsquo;autre partie. L&rsquo;entrepreneur a le droit de mettre fin &agrave; la prestation de service du client en mettant ou en ne mettant pas en &eacute;vidence les causes de cessation. Voici entre autres quelques raisons&nbsp;:</p>
<ul>
<li>Si le client n&rsquo;utilise pas son compte dans un d&eacute;lai de 12 mois, son compte pourrait &ecirc;tre d&eacute;sactiv&eacute; ou supprim&eacute; apr&egrave;s r&eacute;cup&eacute;ration des donn&eacute;s li&eacute;es au compte.</li>
<li>Si les activit&eacute;s men&eacute;es par le client utilisant le compte de Smartlife peuvent nuire &agrave; la r&eacute;putation d&rsquo;affaire de Goteam Sral.</li>
<li>Si en raison de plus de prestations de service des int&eacute;r&ecirc;ts justifi&eacute;s s&rsquo;av&egrave;rent &ecirc;tre profond&eacute;ment l&eacute;s&eacute;s.</li>
</ul>
<h2>8. OTHER</h2>
<p>8.1. Les Parties conviennent qu'elles comprennent le sens et la formulation de cet Accord et le signent volontairement sur la base d'une compr&eacute;hension mutuelle.</p>
<p>8.2. Le Client donne son consentement relatif au traitement de ses informations personnelles en conformit&eacute; avec les exigences de la l&eacute;gislation de la R&eacute;publique de C&ocirc;te d&rsquo;Ivoire &agrave; la signature de cet accord.</p>
<p>8.3. Les diff&eacute;rends qui peuvent ou non survenir lors de l'ex&eacute;cution du pr&eacute;sent Accord et qui ne sont pas r&eacute;gis par le pr&eacute;sent Accord seront r&eacute;gl&eacute;s selon la l&eacute;gislation en vigueure dans &nbsp;la R&eacute;publique de C&ocirc;te d&rsquo;Ivoire.</p>
<p>8.4. Le Client doit respecter les droits du Prestataire sur le site web et sur le logiciel utilis&eacute; pour les Services qui lui sont fournis (brevets, marques de commerce et marques de service, graphiques et droits d'auteur). Le Client doit recevoir le consentement du Prestataire et coordonner avec lui toutes les conditions d'utilisation des droits du Prestataire en le contactant &agrave; l'aide des informations situ&eacute;es sur la page de contact du site. Le Prestataire accorde au Client une licence mondiale libre de redevances, non cessible et non exclusive pour utiliser le contenu qu'il lui fournit dans le cadre des Services. Cette licence &agrave; finalit&eacute; unique donne au Client la possibilit&eacute; d'utiliser les Services comme convenu dans le &nbsp;pr&eacute;sent Accord. L'utilisation, la reproduction, la modification, la diffusion, ou le stockage d'une partie des services, y compris tout type de contenu, &agrave; d'autres fins que l'usage personnel ou non commercial, est interdit si le consentement pr&eacute;alable &eacute;crit du Fournisseur n'a pas &eacute;t&eacute; donn&eacute; au Client. Le Client n'a pas le droit, ni &nbsp;de permettre &agrave; une tierce partie, de copier, de modifier, de cr&eacute;er des travaux d&eacute;riv&eacute;s, de d&eacute;coder la technologie, de d&eacute;compiler, ou de recevoir le code d'origine d'une partie quelconque du Service de quelque mani&egrave;re que ce soit sans le consentement pr&eacute;alable &eacute;crit du Prestataire. Si le Prestataire n'a pas pr&eacute;alablement donn&eacute; ce type de consentement &eacute;crit, cela signifie que le Client ne peut pas transf&eacute;rer les droits d'utilisation des services &agrave; lui-m&ecirc;me, ni d'octroyer de sous- licence, d'accorder des droits pour l'utilisation des services, ou de transf&eacute;rer de quelque autre mani&egrave;re tout type de droits relatifs &agrave; l'utilisation des services ou des responsabilit&eacute;s li&eacute;es aux services.</p>
<p>8.5. Si le client se rend compte d&rsquo;un &eacute;ventuel &nbsp;non-respect du contrat de la part d&rsquo;une personne, le client peut comme ne pas informer l&rsquo;entrepreneur de ce fait et ce, en fonction de son int&eacute;r&ecirc;t &agrave; collaborer.</p>
<p>8.6 Le client peut &eacute;tablir un lien avec une page du site web &agrave; condition que cela soit l&eacute;gal et ne nuise gu&egrave;re &agrave; la r&eacute;putation de l&rsquo;entrepreneur. Pour toute sorte d&rsquo;utilisation des mat&eacute;riaux du site web, veuillez contacter Goteam SARL en utilisant nos coordonn&eacute;es figurant sur la page contactez-nous, du site web.</p>
<p>8-7 Chaque clause de ce contrat est valide et en cas de contestation de toute clause de ce contrat, les autres clauses demeureront valides.</p>
<p>8-8 En aucun cas le site web smartlife.com et/ ou les publications de smartlife faites par des r&eacute;seaux sociaux ne peuvent &ecirc;tre reproduites, commercialis&eacute;es sous quelque forme ou quelque moyen que ce soit y compris la photocopie, l&rsquo;enregistrement ou autre moyen &eacute;lectronique ou m&eacute;canique sans autorisation &eacute;crite de Goteam SARL , cela inclut l&rsquo;utilisation des conditions &lsquo;&rsquo;SMARTLIFE&rsquo;&rsquo; dans n&rsquo;importe quel sorte de domaine ou application pour les appareils mobiles.</p>
<p>8.9. La publication et/ ou la diffusion de toute fausse accusation &agrave; propos de Smartlife, de &nbsp;Goteam SARL&nbsp; &nbsp;ou d&rsquo;un membre du personnel de Goteam SARL &nbsp;par laquelle &nbsp;la r&eacute;putation de la soci&eacute;t&eacute; ou de la personne mentionn&eacute;e est susceptible d&rsquo;&ecirc;tre entach&eacute;e&nbsp; le prestataire m&egrave;nera &nbsp;des actions judiciaires contre l&rsquo;auteur/ diffuseur de la diffamation. Cela inclut explicitement l&rsquo;arr&ecirc;t imm&eacute;diat et d&eacute;finitif du compte de l&rsquo;auteur si celui-ci d&eacute;tient un compte Smartlife.</p>
<p>8.10. La publication de mati&egrave;re diffamatoire peut &ecirc;tre (a) des paroles ou des sons audibles ou (b) des mots destin&eacute;s &agrave; &ecirc;tre lus au toucher ou par la vue, des signes, des &nbsp;gestes ou d&rsquo;autres moyens visuels.</p>
<p>&nbsp;</p>
<h1><strong>Politique de confidentialit&eacute;</strong></h1>
<p>Vous pouvez lire ci-apr&egrave;s les conditions de la politique de confidentialit&eacute; qui pr&eacute;sentent, sous r&eacute;serve des exigences de la R&eacute;publique de C&ocirc;te d&rsquo;Ivoire, les informations sur la collecte de donn&eacute;es, y compris vos donn&eacute;es personnelles, en relation avec les services fournis par Goteam Sarl qui a un statut de payeur de l'imp&ocirc;t sur le revenu sur une base r&eacute;guli&egrave;re conform&eacute;ment au Code fiscal de la R&eacute;publique de C&ocirc;te d&rsquo;Ivoire (<strong>GOTEAM, situ&eacute; &agrave; Abidjan Cocody Angr&eacute; 9<sup>&egrave;me</sup> tranche vers la CNPS, immeuble TERE Lot 703/ilot 31/01 BP 10733 ABJ 01/ Tel +225 45462347/ +225 51505090/+225 22010430/ RCCM&nbsp;: CI-ABJ-2016-B-24324/CC:1646960Q</strong>), ainsi que leur traitement. L'acceptation des Conditions d'utilisation accessibles sur <a href="http://smartlife.com">http://smartlife.com</a> signifie que vous acceptez les dispositions de la pr&eacute;sente Politique de confidentialit&eacute;.</p>
<p>Goteam SARL &nbsp;met un accent particulier sur la protection de la vie priv&eacute;e des Utilisateurs des services et sur la s&eacute;curit&eacute; du traitement de leurs donn&eacute;es personnelles. Les services de traitement des donn&eacute;es personnelles qui sont pr&eacute;sentes dans les formulaires d'inscription ainsi que des donn&eacute;es personnelles collect&eacute;es automatiquement sont effectu&eacute;s en conformit&eacute; avec les dispositions de la loi n&deg;2013-450 du 19 Juin 2013 &nbsp;relative &agrave; la protection des donn&eacute;es &agrave; caract&egrave;re personnel&nbsp; et de la loi n&deg;2013-546 du 30 Juillet 2013 &nbsp;relative aux transactions &eacute;lectroniques &nbsp;. Les Utilisateurs ont le droit d'acc&egrave;s &agrave; leurs donn&eacute;es personnelles et ont le droit de les modifier. Les donn&eacute;es qui sont collect&eacute;es automatiquement ne peuvent pas &ecirc;tre modifi&eacute;es ni effac&eacute;es par les utilisateurs du site web.</p>
<h2>I. Collecte des donn&eacute;es</h2>
<ol>
<li>Donn&eacute;es sp&eacute;cifi&eacute;es par l'utilisateur, y compris ses donn&eacute;es personnelles</li>
</ol>
<p>L'Utilisateur est invit&eacute; &agrave; fournir certains renseignements lors de son inscription, en particulier ses informations personnelles apr&egrave;s son consentement. Ses renseignements personnels pr&eacute;sents dans les formulaires d'inscription sur le site web seront trait&eacute;s uniquement en conformit&eacute; avec la pr&eacute;sente Politique de confidentialit&eacute; relative &agrave; la fourniture de services fournis par le site web, ainsi qu'aux fins sp&eacute;cifi&eacute;es dans les formulaires d'inscription des services correspondants sur le site web. En dehors de cela, ces donn&eacute;es ne peuvent &ecirc;tre trait&eacute;es qu'avec le consentement de l'Utilisateur et uniquement &agrave; des fins licites, y compris aux fins de marketing direct des services, des produits, de la politique de la Soci&eacute;t&eacute; et des soci&eacute;t&eacute;s tierces qui collaborent avec Goteam Sarl</p>
<h2>II. Confidentialit&eacute; des donn&eacute;es</h2>
<ol>
<li>Goteam Sarl ne n&eacute;gociera ni n'&eacute;changera avec des tiers (que ce soit par vente ou location) les renseignements personnels des utilisateurs du site web sans leur consentement. Les donn&eacute;es personnelles des utilisateurs du site web sont accessibles uniquement par les organismes gouvernementaux autoris&eacute;s et EXCLUSIVEMENT apr&egrave;s la demande autoris&eacute;e &agrave; des fins d'enqu&ecirc;te, ainsi que par des tierces parties qui agissent en fonction des demandes autoris&eacute;es &eacute;crites et personnelles fournies par les organismes gouvernementaux lorsque lesdits tiers agissent pour le compte de ces organismes gouvernementaux. Ce sont les exigences de la loi et nous les respecterons.</li>
<li>Goteam Sarl collecte automatiquement des informations sur l'utilisateur relatives aux adresses IP des Utilisateurs du site web et des Utilisateurs des services fournis par le Site. Les donn&eacute;es recueillies de cette mani&egrave;re et les r&eacute;sultats de leur analyse p&eacute;riodique, y compris l'analyse statistique, sont utilis&eacute;s pour estimer la fonctionnalit&eacute; du site et des services. Les donn&eacute;es sur les adresses IP des Utilisateurs du Site sont accessibles uniquement par les organismes gouvernementaux autoris&eacute;s et EXCLUSIVEMENT apr&egrave;s la demande autoris&eacute;e &agrave; des fins d'enqu&ecirc;te, ainsi que par des tierces parties qui agissent selon l'autorisation &eacute;crite et les demandes personnelles donn&eacute;es par les organismes gouvernementaux dans les cas o&ugrave; ces tiers agissent pour le compte de ces organismes gouvernementaux. Ce sont les exigences de la loi et nous les respecterons.</li>
</ol>
<h2>III. Cookies</h2>
<ol>
<li>Le site utilise des cookies, qui sont des fichiers texte stock&eacute;s dans les services de votre PC ou de tout autre appareil, au moyen desquels vous acc&eacute;dez au site web et utilisez les Services.</li>
<li>Les cookies ne sont pas utilis&eacute;s pour obtenir des informations sur les utilisateurs individuels. Ils sont utilis&eacute;s pour l'authentification des utilisateurs, le stockage de leurs param&egrave;tres personnalis&eacute;s et leurs pr&eacute;f&eacute;rences, l'enregistrement de l'&eacute;tat et de la dur&eacute;e de la session de l'utilisateur, le maintien du journal et des statistiques, l'optimisation de la publicit&eacute; sur le site web, le cas &eacute;ch&eacute;ant, ainsi que l'am&eacute;lioration du fonctionnement du site web conform&eacute;ment aux normes web en vigueur. Les cookies peuvent &eacute;galement &ecirc;tre utilis&eacute;s si la Soci&eacute;t&eacute; collabore avec les services de publicit&eacute;, les services de recherche et de statistiques sur Internet, ainsi que les fournisseurs d'applications multim&eacute;dia.</li>
<li>En utilisant les outils disponibles dans les param&egrave;tres de n'importe quel navigateur disponible sur le march&eacute;, vous pouvez &agrave; tout moment modifier les param&egrave;tres associ&eacute;s aux cookies et autres technologies utilis&eacute;es pour le stockage des donn&eacute;es (y compris la technologie de stockage local) dans les param&egrave;tres de confidentialit&eacute; de votre navigateur, notamment en bloquant automatiquement leur utilisation dans les param&egrave;tres du navigateur ou de ses modules, ou, en fonction des outils et technologies utilis&eacute;s, en affichant le rapport d&eacute;taill&eacute; de votre appareil chaque fois que vous entrez sur le site en tant qu'utilisateur final. Des informations d&eacute;taill&eacute;es sur les capacit&eacute;s et l'utilisation des cookies sont s&eacute;lectionn&eacute;es dans les param&egrave;tres de votre navigateur ou de ses modules. Apporter des changements &agrave; ces param&egrave;tres peut conduire &agrave; certaines difficult&eacute;s lors de l'utilisation des Services ou de certaines parties des Services.</li>
</ol>
<h2>IV. Liens</h2>
<ol>
<li>Le site web peut inclure des liens vers des sites tiers et Goteam sarl ne sera pas tenu responsable de la politique de confidentialit&eacute; de ces sites tiers.</li>
<li>Goteam Sarl fournit &eacute;galement un acc&egrave;s aux applications propos&eacute;es par des soci&eacute;t&eacute;s tierces. Les informations collect&eacute;es par Goteam Sarl apr&egrave;s l'ex&eacute;cution de telles applications sont trait&eacute;es conform&eacute;ment &agrave; la pr&eacute;sente Politique de confidentialit&eacute;. Les informations recueillies par les fournisseurs de ces applications sont trait&eacute;es conform&eacute;ment &agrave; la politique de confidentialit&eacute; de ces fournisseurs ou autres soci&eacute;t&eacute;s tierces.</li>
</ol>
<h2>V. Communications</h2>
<ol>
<li>Goteam Sarl peut collecter et stocker les journaux d'utilisation aux fins de la communication avec les Utilisateurs. Goteam Sarl peut collecter et stocker des informations concernant l'adresse &eacute;lectronique ou le(s) num&eacute;ro(s) de t&eacute;l&eacute;phone de l'utilisateur, y compris les messages, la date et la dur&eacute;e des communications, les donn&eacute;es du processus, et les r&eacute;sultats des communications.</li>
<li>Lors de la communication avec les Utilisateurs par t&eacute;l&eacute;phone, courriel, etc., Goteam Sarl peut demander &agrave; l'Utilisateur certaines donn&eacute;es personnelles comme son nom, son adresse &eacute;lectronique et autres donn&eacute;es personnelles associ&eacute;es au contexte de la communication. Ces informations sont utilis&eacute;es uniquement aux fins de lui fournir une assistance technique, de r&eacute;pondre &agrave; ses questions, ou de lui fournir les informations qu'il a demand&eacute;es.</li>
</ol>
<h2>VI. Autres utilisations</h2>
<ol>
<li>Goteam Sarl peut utiliser les donn&eacute;es collect&eacute;es &agrave; des fins de :</li>
</ol>
<p>(a) d&eacute;veloppement de nouvelles fonctionnalit&eacute;s, ainsi que d'am&eacute;lioration des services ;</p>
<p>(b) d&eacute;veloppement de nouveaux services ;</p>
<p>(c) protection des droits de Goteam Sarl. ;</p>
<p>(d) ex&eacute;cution de buts l&eacute;gitimes, poursuivis par Goteam Sarl ou des tiers autoris&eacute;s qui re&ccedil;oivent les donn&eacute;es, si le traitement de ces donn&eacute;es ne va pas &agrave; l'encontre des droits et/ou libert&eacute;s du propri&eacute;taire des donn&eacute;es.</p>
<h2>VII. Droits des utilisateurs en ce qui concerne les donn&eacute;es personnelles</h2>
<ol>
<li>Goteam Sarl permet aux Utilisateurs de faire valoir leurs droits lors du transfert des donn&eacute;es personnelles conform&eacute;ment &agrave; la loi n&deg;2013-450 du 19 Juin 2013 portant la protection des donn&eacute;es &agrave; caract&egrave;re personnel, y compris les droits de demander l'exhaustivit&eacute;, la pertinence, la modification, la suspension &agrave; court terme ou permanente de leur traitement ou la suppression compl&egrave;te des donn&eacute;es personnelles dans le cas o&ugrave; elles seraient incorrectes ou per&ccedil;ues comme contrevenant &agrave; la loi ou comme n'&eacute;tant plus n&eacute;cessaires aux fins pour lesquelles elles ont &eacute;t&eacute; collect&eacute;es. Ils ont le droit de supprimer leurs donn&eacute;es personnelles &agrave; tout moment. Si vous consid&eacute;rez que les m&eacute;thodes utilis&eacute;es pour faire valoir vos droits sont insuffisantes, veuillez envoyer une demande &eacute;crite &agrave; Goteam Sarl</li>
</ol>
<h2>VIII. S&eacute;curit&eacute; des donn&eacute;es personnelles</h2>
<ol>
<li>Goteam Sarl utilise des moyens techniques et organisationnels visant &agrave; maintenir le plus haut standard de s&eacute;curit&eacute; et de protection des donn&eacute;es personnelles des utilisateurs contre les acc&egrave;s non autoris&eacute;s ou l'utilisation incorrecte par des tiers. Les moyens techniques sont mis &agrave; jour en m&ecirc;me temps que le d&eacute;veloppement des nouvelles technologies et des besoins ainsi que des moyens de protection disponibles.</li>
<li>Les moyens organisationnels appliqu&eacute;s garantissent que l'acc&egrave;s &agrave; vos donn&eacute;es personnelles n'est accord&eacute; qu'aux personnes autoris&eacute;es &agrave; utiliser l&rsquo;application Smartlife. Goteam Sarl effectue des contr&ocirc;les r&eacute;guliers du respect des lois correspondantes et de la pr&eacute;sente politique de confidentialit&eacute;. Goteam Sarl collabore avec les organismes gouvernementaux qui sont responsables de la surveillance de la collecte et du traitement des donn&eacute;es personnelles et est pr&ecirc;te &agrave; conformer &agrave; leurs exigences le cas &eacute;ch&eacute;ant.</li>
</ol>
<h2>IX. Amendements de cette Politique de confidentialit&eacute;</h2>
<ol>
<li>Le d&eacute;veloppement de la technologie rend in&eacute;vitable l'apport d'amendements &agrave; cette politique de confidentialit&eacute;. Vous pouvez toujours vous tenir au courant &agrave; tout moment de la derni&egrave;re version des Conditions d'utilisation ici.</li>
<li>Nous nous r&eacute;servons le droit de mettre &agrave; jour et d'apporter des modifications dans les Conditions de Service en publiant le mat&eacute;riel mis &agrave; jour ici. Nous vous recommandons de v&eacute;rifier la politique de confidentialit&eacute; de temps &agrave; autre afin de vous familiariser avec les conditions mises &agrave; jour qui peuvent ou non avoir un impact pour vous.</li>
</ol>
<h2>X. Informations suppl&eacute;mentaires</h2>
<ol>
<li>Si vous avez des questions ou des probl&egrave;mes concernant cette politique de confidentialit&eacute;, veuillez contacter Goteam Sarl en utilisant l'adresse &eacute;lectronique situ&eacute;e sur la page de contact sur le site Web.<a href="<?php echo Router::webroot('webroot/assets/base/doc/cgusmartlife.pdf'); ?>">telecharger les conditions d'utilisation.</a></li>
</ol>
<p>&nbsp;</p>
<p>&nbsp;</p>

</div>
  <?php //echo Router::url('cgusmartlife.pdf'); ?>          